general {
        colors = true
        interval = 2
}

order += "wireless _first_"
order += "ethernet _first_"
order += "volume master"
order += "disk /"
order += "memory"
order += "tztime local"

wireless _first_ {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

ethernet _first_ {
        format_up = "E: %ip (%speed)"
        format_down = "E: down"
}

volume master {
        format = "VOL %volume"
        format_muted = "VOL muted"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}

disk "/" {
        format = "SSD %avail"
}

memory {
        format = "RAM %used | %available"
        threshold_degraded = "300M"
        format_degraded = "RAM LOW %available"
}

tztime local {
        format = "%Y-%m-%d %H:%M:%S"
}
